app/assets/javascripts/users.coffee, app/assets/stylesheets/scaffolds.scss, app/assets/stylesheets/users.scss, app/controllers/users_controller.rb, app/helpers/users_helper.rb, app/models/user.rb, app/views/users/_form.html.erb, app/views/users/edit.html.erb, app/views/users/index.html.erb, app/views/users/index.json.jbuilder, app/views/users/new.html.erb, app/views/users/show.html.erb, app/views/users/show.json.jbuilder, config/routes.rb, db/migrate/20160127130138_create_users.rb, db/schema.rb, test/controllers/users_controller_test.rb, test/fixtures/users.yml, test/models/user_test.rb
=> create user page

app/assets/stylesheets/application.scss, app/assets/stylesheets/static_pages.scss, app/views/layouts/application.html.erb, app/views/static_pages/index.html.erb
細かいところ修正したのと、調べてるうちに色々やりたくなってしまった。
それは別のところにメモっておくとして、pushを間違えてしまったよ。
トップページと共通テンプレートの部分を変更してて（テンプレートは右上に日付を入れただけだけど）、
branchをdesignindexとeditlayoutで分けて上げるべきだった。
一回add . したあと、対象のファイルだけ除外する方法がうまくいかなくて上げてしまったよ・・・・無念。
=> edit main-visual,news,

app/assets/javascripts/welcome.coffee, app/assets/stylesheets/welcome.scss, app/controllers/welcome_controller.rb, app/helpers/welcome_helper.rb, app/views/welcome/index.html.erb, test/controllers/welcome_controller_test.rb
=> 余分なコントローラーを削除

app/views/layouts/application.html.erb
=> datetime bug fixed

app/controllers/users_controller.rb, app/views/users/_form.html.erb, db/migrate/20160224145246_add_icon_div_to_users.rb, db/schema.rb
#19 
現在のユーザーの登録編集ページに、アイコンを選択できるように画面とテーブルを修正。
=> slect icon image #19

app/assets/stylesheets/application.scss, app/views/layouts/_footer.html.erb, app/views/layouts/_header.html.erb, app/views/layouts/application.html.erb
=> add footer

app/assets/javascripts/projects.coffee, app/assets/stylesheets/projects.scss, app/controllers/projects_controller.rb, app/helpers/projects_helper.rb, app/views/layouts/_header.html.erb, app/views/projects/index.html.erb, config/routes.rb, test/controllers/projects_controller_test.rb
=> add projects index page

app/views/users/index.html.erb, app/views/users/show.html.erb
=> close #43 add twitter link

app/assets/stylesheets/application.scss, app/views/layouts/_footer.html.erb
フッター部分がブラウザ幅に被る問題。
position属性をfixにしたうえで、もういっちょ、フッター高さにかぶらない高さのmarginを別divで確保。
=> footer add div

app/assets/stylesheets/application.scss, app/views/projects/index.html.erb
projectページのlayoutを作成。
コンテンツを埋めたらissueはclose。
=> Project layout

app/views/layouts/application.html.erb
=> robots-none

app/views/events/index.html.erb, app/views/events/new.html.erb, db/migrate/20160306072745_add_event_image_url_column.rb, db/schema.rb
=> add event image close #22

app/assets/stylesheets/application.scss, app/controllers/events_controller.rb, app/views/events/index.html.erb
イベントページの画像の登録を修正。
画像の比率を一定にしながら表示するように修正。
=> fixed event image rate and register

app/views/events/index.html.erb, app/views/events/new.html.erb, app/views/events/show.html.erb, app/views/users/index.html.erb, app/views/users/new.html.erb, app/views/users/show.html.erb
登録・もどるボタン関連を修正。
修正方法はイカを参考。
http://zvub.hateblo.jp/entry/20150203/1422946649
close #55
=> link button

app/assets/stylesheets/application.scss
=> text-responsive

app/assets/stylesheets/application.scss, app/views/events/index.html.erb, app/views/events/show.html.erb
イベント一覧、イベント詳細ページに日付表示を挿入。
close #50
=> events.add-date

Gemfile, Gemfile.lock, app/admin/admin_user.rb, app/admin/dashboard.rb, app/admin/event.rb, app/admin/message.rb, app/admin/user.rb, app/assets/javascripts/active_admin.js.coffee, app/assets/stylesheets/active_admin.scss, app/models/admin_user.rb, config/initializers/active_admin.rb, config/initializers/devise.rb, config/locales/devise.en.yml, config/routes.rb, db/migrate/20160309161308_devise_create_admin_users.rb, db/migrate/20160309161311_create_active_admin_comments.rb, db/schema.rb, db/seeds.rb, test/fixtures/admin_users.yml, test/models/admin_user_test.rb
=> add active_admin

app/admin/event.rb, app/admin/message.rb, app/admin/user.rb
=> fix activeadmin model

app/admin/user.rb
admin page で user の twitter_id が更新できない不具合修正。
=> be able to fix twitter_id

Gemfile
unicron を windows で install しようとするとエラーとなるのを回避。
=> windows で出るエラー回避

app/admin/news.rb, app/controllers/static_pages_controller.rb, app/models/news.rb, app/views/static_pages/index.html.erb, db/migrate/20160403040946_create_news.rb, db/schema.rb, test/fixtures/news.yml, test/models/news_test.rb
=> top news be able to update in admin page
